global gcmfaces_dir; gcmfaces_dir='/home/jahn/matlab/gael_class/';
addpath /home/jahn/matlab/gael_class/;
addpath /home/jahn/matlab/gael_class/gcmfaces_IO/;
addpath /home/jahn/matlab/gael_class/gcmfaces_convert/;
addpath /home/jahn/matlab/gael_class/gcmfaces_exch/;
addpath /home/jahn/matlab/gael_class/gcmfaces_maps/;
addpath /home/jahn/matlab/gael_class/gcmfaces_misc/;
addpath /home/jahn/matlab/gael_class/gcmfaces_calc/;
addpath /home/jahn/matlab/gael_class/gcmfaces_smooth/;
addpath /home/jahn/matlab/gael_class/gcmfaces_devel/;
addpath /home/jahn/matlab/gael_class/sample_analysis/;
addpath /home/jahn/matlab/gael_class/sample_processing/;
addpath /home/jahn/matlab/gael_class/ecco_v4/;
